# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 997ce4217bed043e850f2e45aa35c1901d74afa6843a29a9808ce019f6a3d7e6f30006d24199dbf604ff94e6b116a41c66e31bf86166d7c376fceeacbcec7566

test:
  secret_key_base: 030decd14ab55d85d3c9e6996503ad6358677b2d7e7aea6d7bebd309776482d4bfe5d49803f14f059a7b1569c9fb3bf392e8cfccc96a0b02e0e839f2ffb370d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
